name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'architecture_diagrams/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'architecture_diagrams/**'

jobs:
  job-one:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Build Docker image for testing
        run: docker build --target test -t todo_app:test .

      - name: Run Docker container for testing
        run: docker run --rm todo_app:test

  job-two:
    name: Deployment
    runs-on: ubuntu-latest
    needs: job-one
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: production
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/todo_app:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/todo_app:latest
          push: true

      - name: Trigger Azure to pull the latest Docker image
        run: |
          curl -X POST '${{ secrets.AZURE_WEBHOOK_URL }}'
   